---
- hosts: network
  become: yes
  tasks:

    - name: Copy /etc/network/interfaces
      template:
        src: roles/network/templates/interfaces.j2
        dest: /etc/network/interfaces
      notify: reload networking

    - name: Copy Quagga Configuration
      template:
        src: roles/network/templates/Quagga.conf.j2
        dest: /etc/quagga/Quagga.conf
      notify: reload quagga

    - name: Copy Quagga daemons file
      copy:
        src: roles/network/files/daemons
        dest: /etc/quagga/daemons
      notify: restart quagga

  handlers:
    - include: handlers/main.yml
      static: yes
