---
- hosts: localhost
  become: yes
  tasks:
    - name: Copy redis-server
      copy:
        src: roles/localhost/files/redis-server
        dest: /usr/local/bin/redis-server
        mode: 0755
      register: copy_redis

    - name: Copy redis-cli
      copy:
        src: roles/localhost/files/redis-cli
        dest: /usr/local/bin/redis-cli
        mode: 0755

    - name: Start Redis
      become: no
      shell: nohup redis-server &
      when: copy_redis.changed

    - name: Install redis python library
      pip:
        name: redis

    - name: Populate Database
      command: python build_database.py
      when: copy_redis.changed
