---
- hosts: localhost
  become: yes
  tasks:

    # Easier to copy the redis-server and cli binaries directly
    # Instead of installing/building each demo run
    - name: Copy redis-server
      copy:
        src: roles/localhost/files/redis-server
        dest: /usr/local/bin/redis-server
        mode: 0755
      register: copy_redis

    - name: Copy redis-cli
      copy:
        src: roles/localhost/files/redis-cli
        dest: /usr/local/bin/redis-cli
        mode: 0755

    - name: Start Redis
      become: no
      shell: nohup redis-server &
      when: copy_redis.changed

    - name: Install redis python library
      pip:
        name: redis

    # This is the python script that will populate the redis database
    # With the variables used in the network
    - name: Populate Database
      command: python build_redis_database.py
      when: copy_redis.changed
