---
#####
## This could be made more complicated
## But for now, we only demonstrate L2 and L3 config
#####

- hosts: network
  become: yes
  tasks:

    - name: Copy /etc/network/interfaces
      copy:
        src: roles/network/files/blank_file
        dest: /etc/network/interfaces
      notify: reload networking

    - name: Copy Quagga Configuration
      copy:
        src: roles/network/files/blank_file
        dest: /etc/quagga/Quagga.conf
      notify: restart quagga

  handlers:
    - include: handlers/main.yml
      static: yes
