---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Sqlite
      apt:
        name: sqlite
        state: present
      register: install_sql

    # This is the python script that will build the database
    # and populate the table with variables of the network
    - name: Populate Database
      command: python build_sql_database.py
      when: install_sql.changed
